src/app/src/features/eu4/features/map/MapTipContents.tsx
=> Omit controller in map tip when same as owner

src/app/src/features/eu4/hooks/usePanTag.tsx
=> Zoom and pan to capital on country flag click

src/app/src/features/eu4/hooks/useMap.tsx
There is an initial render map race condition where the
query for `eu4MapColors` needed to occur after initial mount, but no
props in dependency array would change to cause a re-render
Closes #29
=> Fix initial map render race condition

src/app/src/features/eu4/features/charts/ChartDrawer.tsx
Add explicit search label like the country select so that we have more
control over the logic of filtering
Closes #31
=> Fix chart module selection filter

src/app/src/components/AppLoading.tsx, src/app/src/features/eu4/SavePage.tsx, src/app/src/features/skanderbeg/SkanderbegSavePage.tsx, src/app/src/pages/eu4/saves/[save_id].tsx, src/app/src/pages/eu4/skanderbeg/[skan_id].tsx, src/app/src/styles/styles.css
=> Add loading icon for remote saves

src/map/src/map.ts
The new map draw messages will include the duration it takes to complete
a map draw as well as any queued requests that were cancelled. This
could help us better diagnose performance issues across a variety of
machines. Testing showed that there normally one viewport draw
cancellation on initial map render, which I don't consider a big deal.
Closes #30
=> Add more detailed map performance diagnostics

Cargo.lock, src/app/src/features/eu4/features/country-details/CountryDetailsDescriptions.tsx, src/app/src/features/eu4/features/country-details/InheritanceLabel.tsx, src/app/src/features/eu4/types/models.ts, src/applib/src/parser.rs, src/eu4game/src/achievements.rs, src/eu4game/src/save_game_query.rs, src/eu4game/src/shared.rs, src/eu4game/tests/it/ironman.rs, src/eu4game/tests/it/playthrough_id.rs, src/wasm-eu4/src/country_details.rs, src/wasm-eu4/src/lib.rs, src/wasm-eu4/src/map.rs
First iteration to get feedback:
(The image shows a 5 year time span, it is actually 4)
=> Add inheritance info to country details

Cargo.lock, src/app/src/features/changelog/changes.tsx, src/app/src/features/engine/worker/eu4/module.ts, src/app/src/features/eu4/features/country-details/CountryDetailsDrawer.tsx, src/app/src/features/eu4/features/country-details/CountryLeaders.tsx, src/app/src/features/eu4/features/map/resources.ts, src/app/src/features/eu4/types/models.ts, src/wasm-eu4/src/country_details.rs, src/wasm-eu4/src/lib.rs
Speedrunning community requested this to get a better idea of generals
used.
=> Add list of leaders to country details drawer

justfile
This should solve the problem where someone trying to extract assets on
a directory with spaces, causes just to interpret the spaces as
delimiting two separate arguments
=> Forward positional arguments to commands

src/wasm-eu4/src/map.rs
When a province reverts to being unowned, the history ledger records the
owner changing to "---". "---" is listed as having a country color of
150, 150, 150. This made the timelapse confusing as migratory tribes
quickly colored their area with this color without actually owning the
land.
This also fixes the color of starting unowned provinces by coloring them
appropriately too.
=> Fix map colors for unowned provinces

src/app/package-lock.json, src/app/package.json
Should fix the moment.js security issue (that we're not effected by as
we're not running moment.js server side)
Ref: #97
=> Update antd from 4.18.8 to 4.19.5

Cargo.lock, Cross.toml, README.md, justfile, src/cli/Cargo.toml, src/cli/src/cmd/compile_assets/tarball.rs, src/cli/src/cmd/tokenize.rs, src/eu4game/Cargo.toml, src/eu4game/src/shared.rs, src/eu4game/tests/it/invalid_ironman.rs, src/eu4game/tests/it/ironman.rs, src/eu4game/tests/it/playthrough_id.rs, src/schemas/benches/schema_benchmark.rs, src/schemas/src/resolver.rs
To optimize speed, size, and compile time every little bit.
=> Use inline flatbuffer tokens everywhere

src/app/package-lock.json, src/app/package.json, src/app/tests/api.test.ts
And then once fetch is native to node, another dependency can be removed
=> Replace axios and form-data test dependencies with undici

Cargo.lock, src/app/src/features/eu4/eu4Slice.ts, src/app/src/features/eu4/features/settings/DateTimeline.tsx, src/app/src/features/eu4/features/settings/Timelapse.tsx, src/wasm-eu4/Cargo.toml, src/wasm-eu4/src/lib.rs, src/wasm-eu4/src/map.rs
https://user-images.githubusercontent.com/2106129/180322721-0082bbff-ea78-4b8e-aee6-08d9abb6be64.mp4
=> Add religion timelapse

src/app/src/components/landing/Home.tsx
=> Show supported savegame version range

src/app/src/features/eu4/features/settings/Timelapse.tsx
Some browsers may have access to more than one codec. Like chrome has
vp8 and vp9, firefox only has vp8, and safari has native mp4 support
(added in this commit).
This commit allows the user to select the desired codec if more than one
codec is available.
If no codecs are present, the recording function is omitted.
=> Allow timelapse codec selection with safari support

Cargo.lock, src/app/src/features/eu4/features/country-details/CountryDetailsDescriptions.tsx, src/app/src/features/eu4/features/country-details/CountryDetailsDrawer.tsx, src/app/src/features/eu4/features/country-details/CountryDiplomacy.tsx, src/app/src/features/eu4/types/models.ts, src/wasm-eu4/src/country_details.rs, src/wasm-eu4/src/lib.rs
=> Add country diplomacy section

src/app/src/features/eu4/features/country-details/CountryLeaders.tsx
=> Fixed non-ruler leader names finishing in 'null'

src/app/src/features/eu4/features/settings/TimelapseEncoder.tsx
Closes #154
Adds in a bitrate that is a function of the canvas size with a minimum of 100 kb/s and a max of 2,000 kb/s. The output seems good enough for now. Ideally the bitrate could also be a function of if terrain is overlaid or what map mode is selected. But we'll keep it simple for now.
[sweden (12).webm](https://user-images.githubusercontent.com/2106129/211953518-f399a5db-de2c-4a8c-9991-58ebcfb1a289.webm)
=> Support VP9 timelapses and define bitrate function

src/app/src/components/viz/index.tsx, src/app/src/features/engine/worker/eu4/module.ts, src/app/src/features/eu4/features/charts/ChartDrawerTitle.tsx, src/app/src/features/eu4/features/charts/DevelopmentTree.tsx, src/app/src/features/eu4/features/charts/Help.tsx, src/app/src/features/eu4/features/charts/IdeaGroupsChart.tsx, src/app/src/features/eu4/features/charts/VizRenderer.tsx, src/app/src/features/eu4/types/models.ts, src/app/src/features/eu4/types/visualizations.tsx, src/cli/src/cmd/compile_assets/continents.rs, src/cli/src/cmd/compile_assets/localization.rs, src/cli/src/cmd/compile_assets/tarball.rs, src/eu4game/src/game.rs, src/wasm-eu4/src/lib.rs
=> Add development tree visualization

src/app/src/features/eu4/features/charts/ChartDrawer.tsx, src/app/src/features/eu4/features/charts/ChartDrawerTitle.tsx, src/app/src/features/eu4/features/charts/GeographicalDevelopmentTree.tsx, src/app/src/features/eu4/features/charts/Help.tsx, src/app/src/features/eu4/features/charts/OwnedDevelopmentStatesTree.tsx, src/app/src/features/eu4/features/charts/VizRenderer.tsx, src/app/src/features/eu4/types/models.ts, src/app/src/features/eu4/types/visualizations.tsx, src/app/src/features/eu4/worker/module.ts, src/wasm-eu4/src/country_details.rs, src/wasm-eu4/src/lib.rs
=> Add owned development states tree

Cargo.lock, src/app/src/features/eu4/store/useLoadEu4.tsx, src/app/src/features/eu4/worker/init.ts, src/cli/Cargo.toml, src/cli/src/cmd/transcode.rs, src/eu4game/Cargo.toml, src/eu4game/src/errors.rs, src/eu4game/src/shared.rs, src/map/index.ts, src/map/src/glResources.ts, src/schemas/Cargo.toml, src/vic3save/Cargo.toml, src/wasm-ck3/Cargo.toml, src/wasm-eu4/Cargo.toml, src/wasm-eu4/src/lib.rs, src/wasm-hoi4/Cargo.toml, src/wasm-imperator/Cargo.toml, src/wasm-vic3/Cargo.toml
With the advent of efficiency with ondemand binary deserialization, reducing memory usage by 70% and increasing performance; the split between the parsing and deserialization phases have been merged.
=> Prefer ondemand binary deserialization over triple pass parser

Cargo.lock, src/app/src/features/eu4/features/info/InfoDrawer.tsx, src/app/src/features/eu4/worker/module.ts, src/wasm-eu4/src/lib.rs
=> Display lucky countries in info drawer

src/app/src/features/eu4/features/map/ProvinceSelectListener.tsx, src/app/src/features/eu4/features/settings/MapExportMenu.tsx, src/app/src/features/eu4/features/settings/Timelapse.tsx, src/app/src/features/eu4/features/settings/TimelapseEncoder.tsx, src/app/src/features/eu4/store/eu4Store.tsx, src/app/src/features/eu4/store/useLoadEu4.tsx, src/map/index.ts, src/map/src/map.ts
This way one can opt to wait until the canvas has reflected the latest viewport changes.
=> Switch to task based draw methods

src/schemas/src/resolver.rs, src/vic3save/src/errors.rs, src/vic3save/src/file.rs
=> improve vic3 error messages on lack of token resolver

src/map/assets/shaders/map.frag
=> Derive province border colors from country colors

src/app/app/api/saves/[saveId]/route.ts
JWTs may not be private, but they are tamperproof, so we check them instead of querying the DB if the user is an admin.
=> Use JWTs for admin check instead of DB query

src/app/app/api/login/steam-callback/route.ts
That way if the steam user name is updated, we update our records too.
This also eliminates the race condition for the check if the user already exists.
=> Sync steam user name on login

src/app/app/components/layout/AppHeader.tsx, src/app/app/features/account/AccountContent.tsx, src/app/app/features/account/SaveCard.tsx, src/app/app/features/account/SessionProvider.tsx, src/app/app/features/account/UserSaveTable.tsx, src/app/app/features/eu4/Eu4Ui.tsx, src/app/app/features/eu4/components/NewestSavesTable.tsx, src/app/app/features/eu4/features/info/InfoDrawer.tsx, src/app/app/features/eu4/features/settings/Timelapse.tsx, src/app/app/features/eu4/features/upload/UploadDrawerContent.tsx, src/app/app/features/skanderbeg/SkanderbegPage.tsx, src/app/app/lib/auth.ts, src/app/app/routes/api.admin.og.ts, src/app/app/routes/api.admin.rebalance.ts, src/app/app/routes/api.admin.reprocess.ts, src/app/app/routes/api.key.ts, src/app/app/routes/api.saves.$saveId.ts, src/app/app/routes/api.saves.ts, src/app/app/routes/api.skan.user.tsx, src/app/app/routes/users.$userId.tsx, src/app/app/server-lib/auth/session.ts, src/app/app/server-lib/errors.ts, src/app/app/server-lib/middleware.ts, src/app/app/services/appApi.ts, src/app/tests/auth.test.ts
This centralizes the authorization logic so it should be pretty easy to add new roles or new permissions.
The frontend and backend now share the same logic too.
=> Introduce attribute based access control

justfile
Previously the `just` scripts would errors if executed on bash < 4.2 (ie: macos) or if imagemagick wasn't installed. This commit relaxes the requirements to make it a bit easier to spin up the dev server without save file analysis.
=> Relax requirements to spin up dev server

src/cli/src/cmd/reprocess.rs, src/eu4game/src/achievements.rs, src/eu4game/src/ext.rs, src/eu4game/src/shared.rs, src/eu4game/tests/it/ironman.rs, src/schemas/benches/schema_benchmark.rs, src/schemas/src/resolver.rs, src/vic3save/src/markets.rs, src/vic3save/src/savefile.rs, src/vic3save/src/stats.rs, src/vic3save/src/vic3date.rs, src/wasm-compress/src/lib.rs, src/wasm-compress/tests/test.rs, src/wasm-eu4/src/savefile/country_details.rs, src/wasm-eu4/src/savefile/map.rs, src/wasm-eu4/src/savefile/mod.rs
Generated with:
```sh
cargo clippy --all --features admin --fix
```
=> Apply automatic clippy lints

justfile
Waiting for postgres healthchecks to pass and using pg_isready with a timeout, there must still be a window of opportunity for the db check to fail with "rejecting connections". This commit reintroduces explicit cross-platform retries to try and make CI less flakey.
=> Improved waiting on db

.github/workflows/ci.yml, justfile
Hopefully this fixes the dependabot being unable to clone the tokens repo.
=> Use actions to clone tokens repo in CI

.devcontainer/Dockerfile, .github/workflows/ci.yml, dev/docker-compose.s3.yml
This commit builds the repo under linux arm to simulate development on a
macos machine (which lacks access to docker).
=> Add arm build in CI

.devcontainer/devcontainer.json
Due to the latest docker compose version not yet being released: https://github.com/devcontainers/features/issues/1297
=> Pin docker compose version

src/app/app/components/layout/auth/SteamLogin.tsx, src/app/app/components/layout/auth/SteamRegister.tsx
Somewhere along the way this page's styles regressed, so I had AI restyle it. 😄 
Before / After:
=> Restyle steam login and register pages

src/app/app/features/eu4/features/country-details/CountryBudget.tsx
The hope is that this provides a better depiction of the budget of a country.
=> Country budget page touchup

src/app/app/components/Table.tsx, src/app/app/features/eu4/features/country-details/CountryInstitution.module.css, src/app/app/features/eu4/features/country-details/CountryInstitution.tsx, src/app/app/features/eu4/features/country-details/institutionSteps.test.ts, src/app/app/features/eu4/features/country-details/institutionSteps.ts, src/app/package-lock.json, src/app/package.json, src/wasm-eu4/src/savefile/institution.rs, src/wasm-eu4/src/savefile/models.rs
Explicitly list out each steps to reach the calculated mana cost to avoid users needing to figure out the calculation by hand.
This also fixes the bug where pdx.tools would recommend exploiting dev at 3.
=> Rework institution page

src/app/app/routes/api.admin.rebalance.ts
Not just the ones with an achievement
=> Admin rebalance all saves that have a score

src/app/app/features/eu4/components/MoraleText.tsx, src/app/app/features/eu4/features/charts/HealthGrid.tsx, src/app/app/features/eu4/features/country-details/CountryDetailsDescriptions.tsx, src/wasm-eu4/src/savefile/country_details.rs, src/wasm-eu4/src/savefile/mod.rs, src/wasm-eu4/src/savefile/models.rs
Better to say "I have no idea" than to give a wrong answer.
This is due to a minimum standing morale of 0.51, which makes it impossible to recover the original morale.
=> Give up on morale calculations if at minimum morale

.devcontainer/Dockerfile, .devcontainer/library-scripts/dependencies.sh, .devcontainer/library-scripts/opt-dependencies.sh
- Node 22
- Just 1.40.0
- Flatbuffers 25.2.10
- Latest google cloud cli
- Binaryen 123
=> Update dev environment

src/map/README.md, src/map/index.ts, src/map/tsconfig.json, src/map/vite-env.d.ts
This way changes can be immediately seen in the UI
=> Support static asset hot reloading for map dev server

.github/workflows/ci.yml, Cargo.lock, src/vic3save/Cargo.toml, src/vic3save/src/bin/cli/main.rs, src/vic3save/src/markets.rs, src/vic3save/tests/it/ironman.rs
imperator, ck3, and vic3 all failed to deserialize (for different reasons). New patches changed how data is encoded.
=> Fix imperator, ck3, and vic3 deserialization
