pdx-tools/pdx-tools

src/app/src/features/eu4/features/country-details/CountryDetailsDrawer.tsx, src/app/src/features/eu4/features/info/InfoDrawer.tsx, src/app/src/features/eu4/features/info/InfoSideBarButton.tsx
When the user clicks on the "Show only X on the map" button in the info
drawer, we show only that tag on the map. It seems reasonable that if
the user were to click the button again, it would reset to the map mode
at the time when the user opened the info drawer.
Closes #13
=> Enable toggle tag filter in info drawer

src/app/src/features/eu4/eu4Slice.ts, src/app/src/features/eu4/features/map/Eu4Canvas.ts, src/app/src/features/eu4/hooks/useMap.tsx
As pointed out in #23 the map renders a couple times too many. The cause
is due to the map payload objects changing (not in structural equality,
but in referential equality). The fix is to not only have the map
payload generated when underlying values change.
=> Reduce map re-renders

src/app/src/styles/styles.css
Moving the select items 'X' from right to left means that the 'X' is now
in the same position relative to whatever it's bordering. This means
that one can more easily spam click to remove nations (though, depending
on how many countries one removes, it may be better to start with a
smaller base set of countries, like players and explicitly include
countries).
Closes #32
=> Move clear select items 'X' from right to left

src/map/src/index.ts, src/map/src/staticResources.ts
When the map repo was integrated into the main repo, some of the map
assets were moved around so that they could be easily positioned in git
lfs to not disturb the weight of the main code and could be easily wiped
as needed.
Unfortunately, I forgot to update the standalone map asset references,
so one couldn't run the map repo anymore.
This commit fixes that issue
Closes #36
=> Fix standalone map asset references

src/app/src/components/landing/AnalyzeBox.tsx, src/app/src/components/landing/Home.tsx, src/app/src/pages/loading.tsx
This also aesthetically rewrites the url to look like the home page so
that downstream functions that look at the url will treat saves loaded
through the external loader and the analyze box (or drag and drop) the same.
Closes #41
=> Splice in external loader sub title

src/app/src/features/eu4/hooks/useMap.tsx
When two consecutive saves are loaded, we preserve the map mode between
the two to ease a sort of comparison. However, we must always calculate
political borders on save load to allow for "paint country borders"
option to work regardless of map mode.
An issue of missing stripes and highlights occurred due to the first
render using this faux color calculation.
Closes #48 
Closes #37
=> Fix initial map render omitting stripes and highlights

src/app/src/components/landing/BrowserCheck.tsx, src/app/src/features/eu4/SavePage.tsx, src/app/src/features/skanderbeg/SkanderbegSavePage.tsx, src/app/src/lib/plausible.ts
Users who have a device where the WebGL max texture size is too small
will have a difficult time diagnosing the problem as they will be
greeted with a black screen. So we add the max texture detection as a
check so users see a warning (and report it as a user metric so we can
see the spread)
Closes  #53
=> Add Webgl max texture size check

src/app/src/features/engine/persistant-canvas-context.tsx, src/app/src/features/eu4/features/map/Eu4Canvas.ts, src/app/src/features/eu4/hooks/useMap.tsx
By setting the map hidden until it is fully drawn we can better guard
against users seeing a flicker of the uninitialized map
Closes #38
=> Fix flicker of uninitialized map

justfile, src/app/next.config.js, src/app/package-lock.json, src/app/package.json, src/app/sentry.client.config.js, src/app/sentry.server.config.js, src/app/src/features/notifications/hooks.ts
As part of the migration to pdx.tools, the sentry environment variable
stopped being [exposed to the browser][1]. This cut the app off from
error reporting, leaving us a bit blind to user errors. The fix is to
export `SENTRY_DSN` as `NEXT_PUBLIC_SENTRY_DSN` so that the browser sees
it.
This commit also updates sentry's library to the latest version.
This commit also removes performance trace sampling so that we won't
have to worry about exceeding our quota again.
[1]: https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser
=> Configure and update sentry to latest

src/app/src/features/eu4/hooks/useMap.tsx
This error isn't noticeable to users and should clear out some sentry
issues
=> Fix canvas undefined errors

src/app/src/features/engine/persistant-canvas-context.tsx
Should also clear out sentry errors that don't affect site behavior.
=> Use RAF to avoid resize observer warnings

src/app/package-lock.json, src/app/package.json
A bit disappointed that dependabot didn't catch that the security warning
would be resolved if the axios test dependency was updated. Native http
client with form data support in node js can't come quick enough.
Ref #73
=> Bump axios from 0.25 to 0.26

src/app/src/features/changelog/changes.tsx, src/app/src/features/eu4/features/map/MapTip.tsx
If someone is panning on the map, the map tip should not be visible.
Closes #76
=> Hide map tip while pointer is down

Cargo.lock, justfile, src/app/src/features/engine/worker/ck3/init.ts, src/app/src/features/engine/worker/eu4/init.ts, src/app/src/features/engine/worker/hoi4/init.ts, src/app/src/features/engine/worker/imperator/init.ts, src/assets/Cargo.toml, src/assets/src/brotli_tee.rs, src/assets/src/main.rs, src/assets/src/tokenize.rs, src/eu4game/Cargo.toml, src/eu4game/build.rs, src/eu4game/src/shared.rs, src/packager/Cargo.toml, src/schemas/build.rs, src/schemas/src/lib.rs, src/schemas/src/tokens.fbs, src/wasm-ck3/Cargo.toml, src/wasm-ck3/src/lib.rs, src/wasm-ck3/src/tokens.rs, src/wasm-eu4/Cargo.toml, src/wasm-eu4/src/lib.rs, src/wasm-eu4/src/tokens.rs, src/wasm-hoi4/Cargo.toml, src/wasm-hoi4/src/lib.rs, src/wasm-hoi4/src/tokens.rs, src/wasm-imperator/Cargo.toml, src/wasm-imperator/src/lib.rs, src/wasm-imperator/src/tokens.rs
First and foremost this updates CK3 support to melt 1.5 save games.
But the more interesting update is that the binary tokens are no longer
compiled into the Wasm. Now when a game module is instantiated, instead
of fetching just the wasm payload, the tokens are fetched too. This was
done for several reasons:
- As a form of code splitting. Now if only one of the payloads (the wasm
or tokens) change, the other doesn't need to be redundantly fetched
too.
- Compile times. Previously it would take 6 minutes (2 to compile, 4 to
optimize) the HOI4 module. Now it is much shorter -- about 12 seconds
- Preparation for a future where token incompatibility is real and we
may need to fetch a different token list depending on the save version
Performance thus far seems unaffected.
=> Decouple binary tokens from Wasm and support CK3 1.5

.gitignore, src/app/src/features/eu4/features/map/Eu4Canvas.ts, src/eu4game/src/achievements.rs, src/eu4game/tests/it/ironman.rs
- Map asset checksums did not change, so we can reuse map assets between 1.31-1.33
- Knights of the Caribbean province requirements changed. Not sure what the best solution is. Some achievements have conditions gated by patch (like voltaire's nightmare with), but changing these province requirements may be seen as more of a bugfix. This should not effect any uploaded save.
- The naples test case is achieved on patch 1.33
This PR should be merged when 1.33 is officially released so that the leaderboard can be recalculated with latest weights.
=> Add support for uploading 1.33 saves

src/app/src/features/engine/worker/eu4/module.ts, src/app/src/features/eu4/eu4Slice.ts, src/app/src/features/eu4/features/settings/DateTimeline.tsx, src/app/src/features/eu4/features/settings/MapSettings.tsx, src/app/src/features/eu4/features/settings/Timelapse.tsx, src/app/src/features/eu4/types/models.ts, src/app/src/lib/downloadData.ts, src/wasm-eu4/src/lib.rs
It is inconvenient for users to drag the date slider around to get a
sense of progression for their world. With these new controls, players
have the ability to advance their world by day, week, month, and year.
=> Add map timelapse controls to map settings

src/app/src/features/engine/GameView.tsx, src/app/src/features/engine/worker/eu4/common.ts, src/app/src/features/engine/worker/eu4/module.ts, src/app/src/features/engine/worker/wasm-worker-context.tsx, src/app/src/features/eu4/features/country-details/CountryDetailsDrawer.tsx, src/app/src/features/eu4/features/map/MapTip.tsx, src/app/src/features/eu4/features/map/ProvinceSelectListener.tsx, src/app/src/features/eu4/hooks/useMap.tsx, src/app/src/hooks/useIsMounted.ts
The error is reproducible when a save is uploaded and then the permalink
is clicked.
We need to reset game analysis, otherwise deeply nested components
within the EU4 view will be triggered and assume that a save is loaded
when reality is that the new save hasn't finished parsing.
=> Reset game analysis on unmount to fix canvas undefined errors

src/app/next.config.js, src/app/package-lock.json, src/app/package.json, src/app/src/components/HelpTooltip.tsx, src/app/src/features/engine/index.tsx, src/app/src/features/engine/persistant-canvas-context.tsx, src/app/src/features/eu4/Eu4CanvasOverlay.tsx, src/app/src/features/eu4/components/DateOverlay.tsx, src/app/src/features/eu4/eu4Slice.ts, src/app/src/features/eu4/features/settings/Timelapse.tsx, src/app/src/features/eu4/features/settings/ToggleRow.tsx, src/app/workers-site/index.ts, src/map/src/map.ts
This feature allows users to capture a timelapse into a video recording
to download and share. This implemented at a high level by using a
[canvas's `captureStream`][2] and piping that to a [`MediaRecorder`][3].
Users may choose what resolution to render the map as well as the how
fast the timelapse progresses.
Conceptually simple, but several problems arose.
Capturing the map's canvas omits UI elements like the current date in a
timelapse, something that seems critical when evaluating a timelapse. To
embed a date in the recording, we'd need to either send text into the
map or we could copy the map's canvas into a separate canvas that uses
the 2d api, which has better support for text and we could record that
one instead. While copying around map canvas data seems inefficient, it
was …
=> Allow recording map timelapse into a video

src/app/src/components/viz/index.tsx, src/app/src/components/viz/visualization-context.tsx, src/app/src/features/eu4/features/charts/ChartDrawer.tsx, src/app/src/features/eu4/features/charts/ChartDrawerTitle.tsx, src/app/src/features/eu4/features/charts/CountriesExpensesBaseTable.tsx, src/app/src/features/eu4/features/charts/CountriesIncomeTable.tsx, src/app/src/features/eu4/features/charts/HealthGrid.tsx, src/app/src/features/eu4/features/charts/IdeaGroupsChart.tsx, src/app/src/features/eu4/features/charts/WarTable.tsx, src/app/src/features/eu4/features/charts/annual-ledger/AnnualLedger.tsx, src/app/src/features/eu4/features/charts/casualties/CountriesArmyCasualtiesTable.tsx, src/app/src/features/eu4/features/charts/casualties/CountriesNavyCasualtiesTable.tsx, src/app/src/lib/csv.ts
The visualizations and data tables in the chart view may not be in
someone's desired format, so this commit adds the ability to download
the data as a csv.
The main implementation oddity is that since the data download button
lives outside any calculations, it relies on the visualizations to set a
function to lazily compute the csv.
=> Add export to csv to chart view

src/app/package-lock.json, src/app/package.json
This fixes a DoS CVE in the underlying busboy. There's discussion in
multer's PR 1097 about why there's not a semver compatible new release
of multer (it would break node v0.10 compatibility).
=> Update multer to 1.4.5-lts

src/cli/src/cmd/tokenize.rs, src/schemas/Cargo.toml, src/schemas/benches/schema_benchmark.rs, src/schemas/src/lib.rs, src/schemas/src/resolver.rs, src/schemas/src/tokens.fbs
All tokens observed have some sort of large gap (8,000 or so) in token
values that picks back up at 10,000.
This commit takes advantage of this observation to splice out this gap
so that we don't store and communicate so many empty strings for the
lookup. Benchmarks confirmed that performance hit is negligble. There is
a savings of around 100 KB uncompressed per token list, which isn't bad,
but these savings tend to vanish after brotli decoding.
=> Splice token gap from lookup

Cargo.lock, src/eu4game/src/models.rs, src/wasm-eu4/src/lib.rs, src/wasm-eu4/src/map.rs
There's something about the province filters that slows down the map
calculation. Since the political timeline doesn't utilize the province
filters, we can skip that, which decreases time to calculate 2-3x
I also took the time to refactor the code a bit so that it should be
more readable and re-usable when it comes time for the religion map
mode.
=> Optimize political map timeline calculations

src/app/src/features/eu4/features/settings/Timelapse.tsx
For whatever reason, there are occassional recording runs that when
transcoding the webm to mp4 will cause ffmpeg to log errors about
duplicate frames. This effects both native and browser ffmpeg (ie: I
could take an exported webm file and see the same errors when manually
transcoding to mp4).
The transcoding process would be extremely slow, requiring minutes
whereas it would normally take seconds. The quality output would also be
horrendous and nothing like the webm.
The fix is to set vsync to passthrough as mentioned here:
https://superuser.com/questions/1308355/ffmpeg-webm-to-mp4-awful-video-quality#comment1944969_1308355
I'm not too well versed in ffmpeg flags but it seems like webm could
have a variable bit rate and that caused friction in the transcode.
=> Fix occassional poor quality and performance of mp4 transcode

src/map/index.html, src/map/src/index.ts, src/map/src/map.ts
This PR now incorporates the device's pixel ratio when rendering the
map.
See: https://www.khronos.org/webgl/wiki/HandlingHighDPI
I haven't noticed too much difference on my side in quality or render
speed (I thought at one point I did, but maybe I'm misremembering)
Closes #77
=> Enable HighDPI rendering

Cargo.lock, src/app/next.config.js, src/app/src/features/engine/hooks/useFilePublisher.ts, src/app/src/features/engine/worker/eu4/module.ts, src/eu4game/src/shared.rs, src/wasm-eu4/src/lib.rs, src/wasm-eu4/src/map.rs
- First pass: parse and deserialize meta data to find out game version for asset fetch
- Second pass: parse gamestate and extract only information needed to know primary country colors so that the renderer can be fully setup
- Third pass: use previously parsed gamestate and deserialize everything else
There is still a bit of a delay between when everything is finished and when the map is shown, but that can be iterated on later.
=> Triple pass parser

src/app/src/features/engine/GameView.tsx, src/app/src/features/eu4/features/map/MapTip.tsx, src/app/src/features/eu4/features/map/ProvinceSelectListener.tsx, src/app/src/features/eu4/features/settings/MapSettings.tsx, src/app/src/features/eu4/features/settings/Timelapse.tsx, src/app/src/features/eu4/features/settings/TimelapseEncoder.tsx, src/app/src/features/eu4/store/eu4Store.tsx, src/app/src/features/eu4/store/useLoadEu4.tsx, src/app/src/features/eu4/types/map.ts, src/app/src/features/eu4/worker/module.ts, src/map/src/map.ts, src/wasm-eu4/src/country_details.rs, src/wasm-eu4/src/lib.rs, src/wasm-eu4/src/map.rs, src/wasm-eu4/src/utils.rs
Tons of improvements. The headlining feature is political timelapse including controllers 
[ethiopia (8).webm](https://user-images.githubusercontent.com/2106129/226768101-44c2365b-455b-4333-854a-4badea76e4dd.webm)
It's not perfect and I place any imperfections on the save format 😄 
- Rebels are not shown on the map as the game does not accurately record when a province has been liberated.
- After a war, the game does not always record provinces being returned back to the owner, so we have to manually track when wars end and re-assign them
- When a list of controllers are recorded for a province on a single day, only the first controller is used, as the game lists all future tag switches as controllers which would otherwise mess with the logic (as a future tag can be an existing AI tag, so …
=> Timelapse and historical map improvements

Cargo.lock, src/app/src/components/viz/index.tsx, src/app/src/features/eu4/features/charts/HealthGrid.tsx, src/app/src/features/eu4/features/charts/Help.tsx, src/app/src/features/eu4/types/models.ts, src/app/src/features/eu4/worker/module.ts, src/wasm-eu4/src/lib.rs
- Table allows one to sort columns and see the raw values without hovering over the cells
- Added more signals of country health:
- Income from tax + production + trade + gold
- Number of buildings
- Best generals / admirals
- Army tradition / Navy tradition / Professionalism
- Number of regiments / ships
- Number of completed ideas
- Removed weak signals of country health:
- prestige
- power projection
- overextension
- innovativeness
Closes #103, as this is now serves the purpose of a global table
Closes #102, as the table shows regiments, professionalism, tradition, and best generals (in addition to manpower)
=> Transition healthmap heatmap to table

Cargo.lock, justfile, src/app/next.config.js, src/app/workers-site/index.ts, src/cli/Cargo.toml, src/cli/src/cmd/compile_assets/tarball.rs, src/cli/src/cmd/tokenize.rs, src/cli/src/cmd/transcode.rs, src/cli/src/main.rs, src/cli/src/storage/zstd_tee.rs, src/eu4game/Cargo.toml, src/schemas/benches/schema_benchmark.rs, src/wasm-ck3/Cargo.toml, src/wasm-compress/Cargo.toml, src/wasm-eu4/Cargo.toml, src/wasm-eu4/src/lib.rs, src/wasm-eu4/src/tokens.rs, src/wasm-hoi4/Cargo.toml, src/wasm-imperator/Cargo.toml, src/wasm-vic3/Cargo.toml
To save on space, pdx.tools stores some binary assets (game data, tokens, map info) precompressed with brotli. This required that these assets be served with the `Content-Encoding: br` header. How to configure this behavior is different per platform (ie: next.js vs cloudflare workers), and some platforms don't allow this configuration at all (cloudflare pages).
So this commit instead stores some assets where compression hardly helps uncompressed (map info). Other content that is destined only to be consumed via Wasm is now stored as zstd compressed and decoded in Wasm.
=> Remove dependence on content-encoding header

src/app/package-lock.json, src/app/package.json, src/app/src/pages/api/saves/[saveId]/file.ts, src/app/src/server-lib/s3.ts, src/app/tests/api.test.ts
Updating to aws4fetch seemed easier than updating to the sdk (v3).
I also like that it is more edge ready.
=> Replace aws sdk (v2) with aws4fetch

src/app/src/features/account/UserPage.tsx, src/app/src/features/account/UserSaveTable.tsx, src/app/src/lib/groupBy.ts, src/app/src/server-lib/db/index.ts
This should make it easier to see the progression of multiple concurrent campaigns. If a playthrough group has a singular, unique filename, that filename is used as the playthrough name, otherwise a randomly generated one is used.
See underlined row for example
=> Group user saves by playthrough name

Cargo.lock, src/app/src/components/DataTable.tsx, src/app/src/components/Input.tsx, src/app/src/features/eu4/features/country-details/CountryInstitution.tsx, src/app/src/features/eu4/features/country-details/CountrySideBarButton.tsx, src/app/src/features/eu4/worker/module.ts, src/app/src/features/skanderbeg/SkanderbegPage.tsx, src/app/src/hooks/useThrottle.tsx, src/cli/src/cmd/compile_assets/mapper.rs, src/cli/src/cmd/compile_assets/tarball.rs, src/eu4game/src/ext.rs, src/eu4game/src/game.rs, src/eu4game/src/lib.rs, src/schemas/src/eu4.fbs, src/wasm-eu4/Cargo.toml, src/wasm-eu4/src/lib.rs, src/wasm-eu4/src/savefile/country_details.rs, src/wasm-eu4/src/savefile/institution.rs, src/wasm-eu4/src/savefile/mod.rs, src/wasm-eu4/src/savefile/models.rs
For the times when you want to know:
- What province you should dev push to minimize mana cost
- How many expand infrastructure to do
- What is the optimal dev to exploit at
Since there are too many dev cost modifiers, the institution module allows users to tweak country wide dev cost modifiers as well as tweak individual provinces. But at least it's a start!
This did require new game data (terrain dev cost modifier).
For now restricted to developers.
=> Add country dev push institution module

.gitignore, Cargo.lock, src/app/src/features/engine/GameView.tsx, src/app/src/features/engine/engineStore.ts, src/app/src/features/engine/hooks/useFilePublisher.ts, src/app/src/features/vic3/CountryStats.tsx, src/app/src/features/vic3/TagSelect.tsx, src/app/src/features/vic3/store/Vic3StoreProvider.tsx, src/app/src/features/vic3/store/index.ts, src/app/src/features/vic3/store/useLoadVic3.ts, src/app/src/features/vic3/store/vic3Store.ts, src/app/src/features/vic3/vic3Ui.tsx, src/app/src/features/vic3/worker/init.ts, src/app/src/features/vic3/worker/types.ts, src/app/src/features/vic3/worker/useVic3Worker.ts, src/vic3save/src/bin/cli/main.rs, src/vic3save/src/bin/cli/stats_cli.rs, src/vic3save/src/lib.rs, src/vic3save/src/savefile.rs, src/vic3save/src/stats.rs, src/vic3save/src/vic3date.rs, src/wasm-vic3/Cargo.toml, src/wasm-vic3/src/lib.rs, src/wasm-vic3/src/models.rs
This PR adds some support for vic3 savefiles, see picture for a demo:
Are you interested in this type of contribution? What I'm mostly interested in adding is the kind of stats show in the picture, perhaps add a graph, compute growth rate, extract some more stats ... but I don't want to commit to much more functionality then shown here. 
Some notes:
* Other games seem to have separate repos for detailed parsing, so I created my own vic3save2. But I'm happy to PR that code somewhere else or copy those files here. 
* I haven't tested with binary saves, so I'm not sure if the deserialisation works correctly there.
* The code needs some cleanup, but happy for any comments!
=> Add some VIctoria 3 support

src/app/src/features/vic3/CountryChart.tsx, src/app/src/features/vic3/CountryStats.tsx, src/app/src/features/vic3/vic3Ui.tsx, src/vic3save/src/bin/cli/stats_cli.rs, src/vic3save/src/savefile.rs, src/vic3save/src/stats.rs, src/wasm-vic3/src/lib.rs, src/wasm-vic3/src/models.rs
Main point  of PR is to show some graph with GDP and it's growth rate, see picture:
* Change front end to add some graphs and support two growth values
* Fix the binary constant issue (it was off by 100k not 10k)
* Add 2 iterators to compute growth rate, 1) GDP one and 2) general one
* Add FlattenedTuple to make managing of zipped stats easier
=> Add growth stats and GDP, GDP/c charts

Cargo.lock, src/app/src/features/vic3/CountryMarket.tsx, src/app/src/features/vic3/vic3Ui.tsx, src/app/src/features/vic3/worker/init.ts, src/vic3save/Cargo.toml, src/vic3save/src/bin/cli/main.rs, src/vic3save/src/bin/cli/markets.rs, src/vic3save/src/lib.rs, src/vic3save/src/markets.rs, src/vic3save/src/savefile.rs, src/wasm-vic3/Cargo.toml, src/wasm-vic3/src/lib.rs, src/wasm-vic3/src/models.rs
Adds a table showing estimated prices of goods in a country's market. This is mainly useful to copy into a production methods simulator spreadsheet.
=> Add approximate goods prices

src/map/assets/shaders/map.frag
Chromium browsers can handle our current shaders very well. No issues.
Firefox is not so good. I narrowed in on the map fragment shader being problematic, so I decided to see if it can be optimized. Turns out it can be!
Before:
```
shaders linked: 1428ms
canvas redrawn: 1910ms
total:          3338ms
```
After:
```
shaders linked:  849ms
canvas redrawn:  282ms
total:          1131ms
```
That's a 3x improvement across the board with much faster map redraws.
Chromium browsers improve but to a lesser extent (and are still much faster than firefox).
I'll need to check to make sure there isn't a regression on mobile browsers.
=> 3x faster shader linkage and map draws with optimized map fragment shader

src/map/assets/shaders/map.frag
Avoid shorthand shader array init syntax, as some
android devices lack support.
Confirmed this fixes the issue seen.
https://stackoverflow.com/a/73322269/433785
=> Fix map shader "no default precision defined" error

Cargo.lock, justfile, src/cli/Cargo.toml, src/cli/src/cmd/compile_assets/tarball.rs
315 KB (33%) bytes saved in transit
Everything seems to work. I know we had to fix the output of PNG to be 32 bits, but maybe we never tried lossless webp 🤷 
If we ever want to support newer or upcoming games, it's probably best to start making sure we already have a proven asset pipeline that can scale with much larger maps.
=> Transition all map assets to lossless webp

src/app/app/api/saves/route.ts, src/app/drizzle-kit.config.ts, src/app/migrations/0004_amusing_penance.sql, src/app/migrations/meta/0004_snapshot.json, src/app/migrations/meta/_journal.json, src/app/package.json, src/app/src/server-lib/db/schema.ts
Currently, there's application level code to check for uniqueness when uploading a save. I believe I originally wrote the code this way to be flexible (flexible in what way remains a mystery).
Well, it's been a few years and that flexibility isn't needed, so let's use unique constraints so the DB can save us from the small race condition.
I'm also on a bit of a kick to minimize the number of SQL statements needed to execute
=> Add unique constraint on save hash column

src/app/app/api/saves/[saveId]/route.ts, src/app/src/server-lib/auth/middleware.ts, src/app/src/server-lib/db/index.ts, src/app/src/server-lib/errors.ts, src/app/src/server-lib/middleware.ts
The `withSave` middleware would issue a `SELECT` (for sometimes more data than needed) that wasn't marked in a transaction with `FOR UPDATE` on patch and delete routes. Thus some race conditions were present.
This commit fixes this by using transactions and checking for permission after the database has been mutated using the returned value from the mutation. If the user didn't have permission, the database is rolled back.
=> Reduce save SQL statements and ask for forgiveness

README.md, justfile
Today I went through and set up the environment manually, and I ran into a number of dependency issues that weren't discussed in the guide, so I updated the guide accordingly.  I also noticed that the justfile used 'docker-compose', which is no longer compatible with the v2 syntax 'docker compose' and updated that accordingly.
=> Update to docker compose v2 syntax, and update manual build environment guide

Cargo.lock, src/api/Cargo.toml, src/api/src/main.rs, src/cli/Cargo.toml, src/eu4game/Cargo.toml, src/vic3save/Cargo.toml
~~Block on lack of `with_graceful_shutdown` replacement~~
~~Probably best to upgrade to the rust http 1.0 ecosystem in lockstep, so waiting on aws-sdk https://github.com/awslabs/aws-sdk-rust/issues/977~~ (removed AWS)
=> Update from axum 0.6 to 0.7

src/map/assets/shaders/xbr.frag
Playing around with puppeteer rendering the page and found out that mountains and seas weren't being rendering properly due to conditionals being untrue. Adding tolerance to these conditions fixed the issue.
Before: ![image](https://github.com/user-attachments/assets/a02b91d1-e5d7-49ff-bf59-e9d57c360b9e)
After: ![image](https://github.com/user-attachments/assets/86aef751-9d7e-42bf-aa4b-3b8e5ba138a0)
=> Add alpha tolerance when calculating terrain

dev/docker-compose.test.yml, src/app/.env.development, src/app/app/api/saves/[saveId]/og/route.ts, src/app/app/api/saves/route.ts, src/app/src/components/head/HtmlHead.tsx, src/app/src/pages/eu4/saves/[save_id].tsx, src/app/src/server-lib/og.ts
This works by running puppeteer to execute the page and take a screenshot.
The screenshot is then saved in s3 as a cache.
=> Add og preview images to save links

src/map/index.ts, src/map/src/index.ts, src/map/src/map-worker-bridge.ts
Defining the type in comlink exposure file caused
some headaches with vite, so move the definition
to a side-effect free export file.
=> Optimize MapWorker type definition

Cargo.lock, justfile, src/api/Cargo.toml, src/api/src/main.rs, src/app/package-lock.json, src/app/package.json, src/app/src/server-lib/og.ts
The sharp dependency deployment hack wasn't amazing, so this moves the png to webp screenshot conversion to the API server.
Perhaps in the future, an image CDN can be used as screenshots tend to take longer than I'd like to load.
=> Move screenshot transformation to api server

.github/workflows/ci.yml, justfile
It's expected that contributors won't have the binary tokens available, and it's too common that I break this workflow. Let's guard against it by having CI test with token and without token flows.
CI has also been updated to test the PR logic. Previously it would only test the base code, which would lead to errors slipping by.
=> Update CI to test no token builds

.devcontainer/Dockerfile, .devcontainer/library-scripts/opt-dependencies.sh, justfile
I'm unable to cut a release due to a glibc issue with cross and build scripts. See issue: https://github.com/cross-rs/cross/issues/724
This PR removes cross and instead directly builds it via the target, which is achieved by installing the `musl-tools` package.
=> Remove dependence on cross

Cargo.lock, Cargo.toml, src/api/Cargo.toml, src/applib/Cargo.toml, src/cli/Cargo.toml, src/eu4game-data/Cargo.toml, src/eu4game/Cargo.toml, src/schemas/Cargo.toml, src/vic3save/Cargo.toml, src/wasm-app/Cargo.toml, src/wasm-ck3/Cargo.toml, src/wasm-compress/Cargo.toml, src/wasm-eu4/Cargo.toml, src/wasm-hoi4/Cargo.toml, src/wasm-imperator/Cargo.toml, src/wasm-vic3/Cargo.toml
This way, it makes it easier to track what dependencies are use and be able to bump a instance across all members at once.
=> Move dependency declarations to workspace root

src/app/app/components/DataTable.tsx, src/app/app/components/Table.tsx, src/app/app/features/eu4/features/charts/HealthGrid.tsx
This commit adds the ability to reorder columns in the DataTable component by dragging and dropping the column header.
The healthgrid is the first table to receive this feature.
=> Add Column reordering

src/app/app/features/eu4/features/settings/Timelapse.tsx
The timelapse of short saves, those that only cover maybe a few dozen years, will be too fast with the default speed of 8 years per second.
This commit updates the default, such that the default timelapse will last at least 20 seconds.
=> Dynamic default timelapse speed based on length of save

src/app/app/features/eu4/features/settings/Timelapse.tsx
This way there isn't any layout shift depending on the charcters used in the date (ie: "0" is wider than "1").
=> Use a monospace font for timelapse date

src/app/app/features/eu4/features/charts/IdeaGroupsChart.tsx
This makes them consistent with the other idea groups (ie: even if no occurences, they will still be shown in the chart).
=> Include 1.35 introduced idea sets as seed ideas

src/cli/src/cmd/compile_assets/tarball.rs
This would throw off the instutituion system, which assumed a dev cost modifier of 0%.
=> Fix incorrect mountain association

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/ci.yml, .gitignore
Tried to run a test in devcontainer vscode, but it failed due to cargo not being found. This commit should make vscode aware of the mise tools.
=> Additional mise configuration

src/cli/src/rawbmp/bmp.rs, src/cli/src/rawbmp/mod.rs
They previously weren't implemented correctly and the tests failed when the for loop iterator was actually written correctly.
=> Fix rawbmp Iterator::size_hint implementations

src/vic3save/tests/it/ironman.rs
Tokens were updated which impacted the melted snapshot.
It was only a single token in the AI focus realm, so I it shouldn't have any gameplay impact.
=> Update vicsave to Vic3 1.9

src/app/app/features/eu4/store/eu4Store.tsx, src/app/app/features/eu4/store/useLoadEu4.tsx
Currently when one toggles different map modes, the initial country colors (for the latest date of the save), is detached from the very start and will cause an exception -- resulting in requiring two clicks to change the map mode.
=> Fix referencing detached country color buffers

src/pdx-assets/src/cli/compile.rs, src/pdx-assets/src/images/imagemagick.rs
When writing docs on native windows development, I encountered an issue with mise that it is unable to accept arguments with spaces: https://github.com/jdx/mise/discussions/6119
```
mise run assets:compile 'D:\games\steam\steamapps\common\Europa Universalis IV'
```
Auto-detecting the EU4 installation when no argument is provided, side steps the issue.
=> Auto-detect Steam installation for asset compilation

.config/mise.toml
Having wasm-opt overwrite the original file makes it so we don't have to have platform specific wasm optimization steps to move files around.
=> Simplify wasm-opt task

src/pdx-assets/src/eu4/compiler.rs, src/pdx-assets/src/images.rs, src/pdx-assets/src/images/imagemagick.rs
The root problem is that when generating images with multiple sizes (e.g., for responsive images), the code that adds size suffixes to the output JSON. The fix is to ensure that only a single JSON file is emitted per set of montage requests.
=> Fix missing advisor images with multi-montage requests
